blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('published/<int:pk>', toggle_activity, name='toggle_activity'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from catalog.sitemaps import ProductSitemap

sitemaps = {

    'product': ProductSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('django-check-seo/', include('django_check_seo.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}
class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    date = models.DateTimeField(auto_now=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}, дата публикации {self.date}'

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blog.models import Blog
from pytils.translit import slugify

class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'is_published', 'views_count',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset



class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'is_published', 'views_count',)
    #success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()

    return redirect(reverse('blog:list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
               <div class="card-body">
                   <form method="post">
                       {% csrf_token %}
                       <p>Хотите удалить материал "{{ object.title }}"?</p>

                       <button type="submit" class="btn btn-danger">Подтверждение удаления</button>
                       <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>


                   </form>
               </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content%}

    <div class="container">
        <div class="row">

            <div class="col-md-4">
                <img src="{% mediapath object.image %}" />
            </div>


            <div class="col-md-8">
                <h2>{{ object.title }} ({{ object.slug }})</h2>
            </div>
            <div class="card-body">
            <p>
                {{ object.body }}
            </p>
            </div>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}
            </div>


        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
               <div class="card-body">
                   <form method="post">
                       {% csrf_token %}
                       {{ form.as_p }}
                       <button type="submit" class="btn btn-success">
                           {% if object %}
                                Сохранить
                           {% else %}
                                Создать
                           {% endif %}
                       </button>

                   </form>
               </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Новости и объявления</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object.title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blog:view' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                    <a href="{% url 'blog:edit' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'blog:delete' object.pk %}"
                       class="btn btn-sm btn-outline-danger">Удалить</a>
                </div>
                {% if object.is_active %}
                    <a class='btn btn-warning' href="{% url 'blog:toggle_activity' object.pk %}">Снять с публикации</a>
                {% else %}
                    <a class='btn btn-success' href="{% url 'blog:toggle_activity' object.pk %}">Опубликовать</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}