blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('published/<int:pk>', toggle_activity, name='toggle_activity'),

]

catalog/urls.py
from django.contrib import admin
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductCreateView, ProductListView, ProductDetailView, ProductUpdateView, \
    ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_form'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='product_confirm_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from catalog.sitemaps import ProductSitemap

sitemaps = {

    'product': ProductSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('django-check-seo/', include('django_check_seo.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify_email, generate_password

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify/<str:key>/', verify_email, name='verify_email'),
    path('generate_password/', generate_password, name='generate_password'),
]

catalog/models.py
from django.db import models
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f'{self.name}, {self.description}'

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ('name',)


class Product(models.Model):
    STATUS_CREATED = 'created'
    STATUS_MODERATED = 'moderated'
    STATUS_PUBLISHED = 'published'
    STATUSES = (
        (STATUS_CREATED, 'добавлен'),
        (STATUS_MODERATED, 'на модерации'),
        (STATUS_PUBLISHED, 'опубликован')
    )
    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='категория', **NULLABLE)
    price = models.IntegerField(verbose_name='цена')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    change_date = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='автор', **NULLABLE)
    status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_MODERATED, verbose_name='статус')

    def __str__(self):
        return f'{self.name}, {self.category}, {self.price} руб/кг'

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        permissions = [
            ("set_active_status", "Can activate product"),
            ("change_product_description", "Can change product description"),
            ('change_product_category', 'Can change product category'),
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version = models.CharField(max_length=20, verbose_name='номер версии')
    version_name = models.CharField(max_length=20, verbose_name='название версии')
    is_active = models.BooleanField(default=False, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.version_name}, {self.version}'

    class Meta:
        verbose_name = "версия"
        verbose_name_plural = "версии"

catalog/forms.py
from django import forms
from catalog.models import Product, Version

forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    #version = forms.ModelChoiceField(queryset=Version.objects.all(), empty_label=None, label='Версия продукта')

    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'price', 'preview')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if cleaned_data in forbidden_words:
            raise forms.ValidationError('Вы вводите запрещенные слова')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        if cleaned_data in forbidden_words:
            raise forms.ValidationError('Вы вводите запрещенные слова')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'status',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        user = self.request.user
        if user.is_staff or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(status=Product.STATUS_PUBLISHED)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        for product in context_data['object_list']:
            active_version = Version.objects.filter(product=product, is_active=True).last()
            if active_version:
                product.active_version_number = active_version.version
                product.active_version_name = active_version.version_name
            else:
                product.active_version_number = None
                product.active_version_name = None
        return context_data


class ProductDetailView(DetailView):
    model = Product


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone_number = request.POST.get('phone_number')
        message = request.POST.get('message')
        print(f"Имя: {name}, Телефон: {phone_number}, Сообщение: {message}")
    context = {
        'title': 'Контакты',
    }

    return render(request, 'catalog/contacts.html', context)


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductModeratorForm
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.change_product'

    def test_func(self):
        user = self.request.user
        product = self.get_object()

        if product.owner == user or user.is_staff:
            return True
        else:
            return False


    def handle_no_permissions(self):
        return redirect(reverse_lazy('product_list'))


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.delete_product'

catalog/templates/catalog/add_product.html
{% extends 'catalog/base.html' %}

{% block content%}

<div class="col-lg-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Добавить продукт</h4>
        </div>
        <div class="card-body">
            <form method="post" action="" class="form-floating">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="name">Название продукта</label>
                    <input type="text" name="name" class="form-control" placeholder="Название" required>
                </div>

                <div class="mb-3">
                    <label for="name">Описание продукта</label>
                    <input type="text" name="description" class="form-control" placeholder="Информация о продукте"
                           required>
                </div>

                <div class="mb-3">
                    <label for="name">Категория</label>
                    <input type="text" name="category" class="form-control"
                           placeholder="Категория (бакалея, овощи, фрукты, готовая продукция)" required>
                </div>

                <div class="mb-3">
                    <label for="name">Цена</label>
                    <input type="text" name="price" class="form-control" id="name" placeholder="Цена за кг" required>
                </div>



                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Добавить продукт</button>
            </form>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        <img src="/media/logo_astor.jpg" width="110" height="100">
    </h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}

        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Blog</a>



    </nav>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>

            {% block content %}
            {% endblock %}

        </div>
    </div>
</div>


<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Хайдукова и Ко&copy; {% now 'Y' %}</p>

    </div>
</footer>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">Телефон</td>
                            <td>+7(343)379-03-00</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Екатеринбург, ул. 8 Марта, 212</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content%}

    <div class="container">
        <div class="row">
            <!-- Левая часть с изображением -->
            <div class="col-md-4">
                <img src="{% mediapath object.image %}" />
            </div>

            <!-- Правая часть с информацией о товаре -->
            <div class="col-md-8">
                <h2>{{ product.name }}</h2>
                <p>Описание товара: {{ product.description }}</p>
                <p>Цена: {{ product.price }} руб.</p>
                <button class="btn btn-primary">Положить в корзину</button>
            </div>


        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
               <div class="card-body">
                   <form method="post">
                       {% csrf_token %}
                       <p>Хотите удалить товар "{{ product.name }}"?</p>

                       <button type="submit" class="btn btn-danger">Подтверждение удаления</button>
                       <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>


                   </form>
               </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content%}

    <div class="container">
        <div class="row">
            <!-- Левая часть с изображением -->
            <div class="col-md-4">
                <img src="/media/{{ product.preview }}/" width="500" height="555">
            </div>

            <!-- Правая часть с информацией о товаре -->
            <div class="col-md-8">
                <h2>{{ product.name }}</h2>
                <p>Описание товара: {{ product.description }}</p>
                <p>Цена: {{ product.price }} руб.</p>
                <p>Создатель: {{ product.owner }} </p>
                <div class="">

                        {% if perms.catalog.change_product or object.owner == user %}
                        <a href="{% url 'catalog:product_update' object.id %}" type="button" class="btn btn-outline-primary">изменить</a>
                        {% endif %}
                        {% if perms.catalog.delete_product %}
                        <a href="{% url 'catalog:product_confirm_delete' object.id %}" type="button" class="btn btn-outline-primary">удалить</a>
                        {% endif %}

                    </div>

                <div class="card-footer">
                            {% if object.active_version_name %}
                            <p>Номер активной версии: {{ object.active_version_number }}<br>
                                Название: {{ object.active_version_name }}</p>
                            {% else %}
                            <p>Номер активной версии: отсутствует <br>
                                Название: отсутствует </p>
                            {% endif %}
                        </div>


                <button class="btn btn-primary">Положить в корзину</button>
            </div>
<div class="col-6">

        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            {% if object %}
                            Редактирование товара
                            {% else %}
                            Добавление товара
                            {% endif %}
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>

</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}
<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:product_form' %}">Добавить продукт</a>

  {% endif %}
</div>

<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">

                    <div class="card-body">
                        <p class="card-text">{{ object }}</p>
                        <p class="card-text">{{ object.owner }}</p>

                        <p class="card-text">
                            {{ object.description|truncatechars:50 }}
                        </p>
                        <img src="{% mediapath object.preview %}" width="100" height="111">



                        <div class="card-footer">
                            {% if object.active_version_name %}
                            <p>Номер активной версии: {{ object.active_version_number }}<br>
                                Название: {{ object.active_version_name }}</p>
                            {% else %}
                            <p>Номер активной версии: отсутствует <br>
                                Название: отсутствует </p>
                            {% endif %}
                        </div>


                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if user.is_authenticated %}
                                <a href="{% url 'catalog:product_detail' object.id %}"
                                   class="p-2 btn btn-outline-primary">Купить</a>
                                {% else %}
                                <a href="{% url 'users:login' %}"
                                class="p-2 btn btn-outline-primary">Купить</a>
                                {% endif %}
                                {% if user.is_authenticated %}
                                <a href="{% url 'catalog:product_update' object.id %}"
                                   class="p-2 btn btn-outline-primary">Изменить</a>
                                {% else %}
                                <a href="{% url 'users:login' %}"
                                class="p-2 btn btn-outline-primary">Изменить</a>
                                {% endif %}
                                {% if perms.catalog.delete_product %}
                                <a href="{% url 'catalog:product_confirm_delete' object.id %}"
                                   class="p-2 btn btn-outline-primary">Удалить</a>

                                {% endif %}



                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>